version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres_transporte
    restart: always
    environment:
      POSTGRES_DB: transporte_medellin
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
